import { CSSProperties } from 'react';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Gmail Signature Template',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: DefaultProps) {
  const main: CSSProperties = {
    backgroundColor: '#fff',
    fontFamily: '-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,Oxygen-Sans,Ubuntu,Cantarell,"Helvetica Neue",sans-serif',
  };

  return (
    <html lang='en'>
      <body suppressHydrationWarning={true} style={main}>{children}</body>
    </html>
  );
}
